Improve givbacks input revision
Giveth/givback-calculation pull request #40
Opened 2024-02-21 12:49 UTC by mohammadranjbarz

2024-02-21 15:03 UTC, divine-comedian commented
@mohammadranjbarz - looks like there is some regression in the code 

on the current deployment we do not ask for the `givBacksRelayerAddress` - however in this branch now it is back again 

![image](https://github.com/Giveth/givback-calculation/assets/67759413/c493a011-2aa6-4cec-89bc-a63721e00967)

Are you sure you started working on the correct branch?

2024-02-21 15:29 UTC, divine-comedian requested changes

2024-02-21 15:29 UTC, divine-comedian commented on src/index.ts
> +        givRelayerAddress,
We should not be getting this anymore from the API call - this is not how it is current deployment

2024-02-22 07:02 UTC, mohammadranjbarz commented
Soryy @divine-comedian my PR is https://github.com/Giveth/givback-calculation/pull/41 I close this one, my target branch would be yours, because I just wanted to make some changes on your PR

2024-02-22 07:02 UTC, closed without merging